os:
        - linux
launage: php
php:
        - '7.3'
before_script:
        - composer self-update
        - composer install --no-interaction
        - npm install
script:
        - bash echo "test"
